# -*- coding: utf-8 -*-
"""board

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-kgSylB1HYxESjzigtiCpQZdMKOiRxCP
"""

board = [['-','-','-'],['-','-','-'],['-','-','-']]
def print_board():
  for i in range(0,3):
    print(board[i])
print("Printing board")
print_board()